CREATE PROCEDURE [batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].[test Extraction Respects Minimum]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].ACTUAL') IS NOT NULL DROP TABLE [batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].ACTUAL;
	IF OBJECT_ID('[batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].EXPECTED') IS NOT NULL DROP TABLE [batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].EXPECTED;

	EXECUTE [tSQLt].[FakeTable] '[stagedSchema].[srcObject_stg]';

	EXECUTE [TestHelpers].[DataBuilder_srcSchema_srcObject] @Id = 1, @Contents = 11;
	EXECUTE [TestHelpers].[DataBuilder_srcSchema_srcObject] @Id = 2, @Contents = 22;
	DECLARE @SpecifyMin BINARY(8) = @@DBTS;
	EXECUTE [TestHelpers].[DataBuilder_srcSchema_srcObject] @Id = 3, @Contents = 33;

	EXECUTE [tSQLt].[FakeTable] '[batchSchema].[srcObject_batches]';
	EXECUTE [TestHelpers].[DataBuilder_batchSchema_srcObject_batches] @BatchId = 1, @BatchStart = '2000-01-01', @MinimumValue_IncrementalColumnName = @SpecifyMin;

	--ACT
	EXECUTE [batchSchema].[srcObject_stageNextBatch_Step2_ExtractBatch_usp];
	
	SELECT 
	 [Id]
	,[Contents]
	,[BatchId]
	INTO [batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].ACTUAL
	FROM [stagedSchema].[srcObject_stg];

	--ASSERT
	CREATE TABLE [batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].EXPECTED (
		 [Id]		INT
		,[Contents]	INT
		,[BatchId]	INT
	);
	INSERT INTO [batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].EXPECTED (
	 [Id]
	,[Contents]
	,[BatchId]
	) VALUES (3,33,1)
	;

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].EXPECTED', @Actual = '[batchSchema__srcObject_stageNextBatch_Step1_StartBatch_usp].ACTUAL';

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
